use std::chrono instead of boost timer
ApexAI/static_exception pull request #1
Opened 2021-08-24 23:19 UTC by flynneva

this should fix the ci build errors I think

2021-08-24 23:30 UTC, flynneva commented
also had to update the GCC version in `src/exception_memory_pool.cpp` file line `24` to get it to compile on my workstation (run `gcc --version` to see your version)

2021-08-24 23:32 UTC, flynneva commented
![image](https://user-images.githubusercontent.com/6157095/130703108-860fdbe9-16a6-45e7-9553-b74e704fb428.png)

2021-08-25 14:48 UTC, flynneva commented
realized late last night that we should probably also be printing out the cpu time as well using `std::clock`. added that in there this morning so now the test looks like this:

![image](https://user-images.githubusercontent.com/6157095/130812887-0c468ac0-60f2-4d30-b1ab-42da0c4203f4.png)

2021-08-25 18:03 UTC, kylemarcey requested changes

2021-08-25 18:03 UTC, kylemarcey commented on src/exception_memory_pool.cpp
> +#if __GNUC__==9 && __GNUC_MINOR__==3 && __GNUC_PATCHLEVEL__==0
I would probably just make it check that the version is at least 5.4 so it doesn't have to be updated every time someone wants to build. I think these APIs should be reasonably stable

2021-08-25 18:03 UTC, kylemarcey commented on test/static_exception_test.cpp
> +#include <ctime>
You should include `chrono` as well

2021-08-25 18:03 UTC, kylemarcey commented on test/static_exception_test.cpp
> +  auto t_start = std::chrono::high_resolution_clock::now();
`steady_clock` should be used when measuring a duration since it's guaranteed to be monotonic

2021-08-25 23:16 UTC, merged